name: CI
# Workflow file for windows
on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  Windows:
    name: build-ubuntu-latest
    runs-on: [ubuntu-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
          submodules: recursive

    - name: boost
      run: sudo apt-get update && sudo apt-get install -yq libboost1.65-dev
      
    - name: Running cmake 
      run: |
        cd ${{ github.workspace }}
        mkdir build
        cmake -Bbuild -H.
        cmake --build build/ --target all

    
